apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: supabase-certificate
spec:
  secretName: supabase-tls-secret
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - <domain>
