# supabase-values.yml

postgrest:
  enabled: true
  auroraEndpoint: <aurora_endpoint>

auth:
  enabled: true

realtime:
  enabled: true

storage:
  enabled: true
  s3Endpoint: <s3_endpoint>
  s3Bucket: <s3_bucket_name>
  s3AccessKey: <s3_access_key>
  s3SecretKey: <s3_secret_key>

kong:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: <ingress_host>
        paths:
          - path: /
